### ISSUE TITLE
improve API documentation

### ISSUE THREAD

**Issue by archenemies** [bnaras/cubature#26]
I'm looking at the following arguments for the documentation of `hcubature` in the R wrapper package:

    f       The function (integrand) to be integrated
    fDim    The dimension of the integrand, default 1, bears no relation to the dimension of the hypercube

Compare this with the documentation in the original C library:

    This integrates a function F(x), returning a vector of FDIM integrands, where x is a DIM-dimensional vector ranging from XMIN to XMAX (i.e. in a hypercube XMINᵢ ≤ xᵢ ≤ XMAXᵢ).

and

    The integrand function F should be a function of the form:

    int f(unsigned ndim, const double *x, void *fdata,
          unsigned fdim, double *fval);

It would be useful to improve the R documentation so that it is as detailed as these examples from the C library. In particular in the R documentation, it should be explicitly stated what the arguments of `f` are. If `f` is supposed to return a numerical vector of length `fDim`, then this can be stated explicitly in the documentation, not just hinted at. What is the relation between `fDim` and `nComp` in other functions? Saying "bears no relation to the dimension of the hypercube" is helpful, but telling us what it *does* bear a relation to would be more helpful. Thanks.

**Comment by bnaras** [comment]
Well, I'm all for improving the documentation.  Make a PR.

**Comment by archenemies** [comment]
If you want to answer the questions I asked about the API in your own words, then I am happy to give examples of how they could be phrased more clearly in the documentation.

**Comment by archenemies** [comment]
I now have it working with the `cuhre` and `hcubature` interfaces.

nComp and fDim are the same thing

The function f is supposed to return a matrix with fDim rows, one column per input point. I guess the input to f is also a matrix, in my case f's domain is one dimensional, but I would imagine in the multidimensional case the input has the same format as the return value but with length(lowerLimit) rows.

Thank you for this great software.
