### ISSUE TITLE
Installation Error on CentOS

### ISSUE THREAD

**Issue by genomaths** [bnaras/cubature#29]
When trying the installation of 'cubature' R package in CentOS, I got the following report:

> devtools::install_git("https://github.com/cran/cubature.git")

In file included from ./src/divonne/common.c:14:0,
                 from ./src/common/CSample.c:77,
                 from ./src/divonne/Divonne.c:14:
./src/divonne/Split.c: In function ‘SolveEqs’:
./src/divonne/Split.c:119:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int first_time = 1 ; c >= cut; --c) {
   ^
./src/divonne/Split.c:119:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [libcuba.a(Divonne.o)] Error 1
make[1]: Leaving directory `/tmp/RtmpzyLsw8/R.INSTALLec444ba5a993/cubature/src/Cuba-4.2'
make: *** [cuba.ts] Error 2
ERROR: compilation failed for package ‘cubature’
* removing ‘/home/rus547/R/x86_64-redhat-linux-gnu-library/3.6/cubature’
Error: Failed to install 'unknown package' from Git:

Similar result trying directly from RStudio:

In file included from ./src/divonne/common.c:14:0,
                 from ./src/common/CSample.c:77,
                 from ./src/divonne/Divonne.c:14:
./src/divonne/Split.c: In function ‘SolveEqs’:
./src/divonne/Split.c:119:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int first_time = 1 ; c >= cut; --c) {
   ^
./src/divonne/Split.c:119:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [libcuba.a(Divonne.o)] Error 1
make[1]: Leaving directory `/tmp/Rtmp3rE7YX/R.INSTALLf34b5f9fe4f1/cubature/src/Cuba-4.2'
make: *** [cuba.ts] Error 2
ERROR: compilation failed for package ‘cubature’
* removing ‘~/R/x86_64-redhat-linux-gnu-library/3.6/cubature’
Warning in install.packages :
  installation of package ‘cubature’ had non-zero exit status

There is not problem at all on Linux OS.
 
Would you please help me with this issue?
Best,
Robersy

**Comment by tstev** [comment]
Hi @genomaths, I ran into the same problem when trying to install `MCMCglmm` package on Linux which depends on `cubature`. I found a working solution that might work for you too, hopefully. I added `CFLAGS=-std=gnu99` to the file `file.edit("~/.R/Makevars")`. Then installed as normal.

**Comment by genomaths** [comment]
Hi @tstev  Thank you for your support
Your suggestion worked for me as well
