### ISSUE TITLE
Is cubintegrate always returning absolute errors?

### ISSUE THREAD

**Issue by eguidotti** [bnaras/cubature#32]
Hello @bnaras and thank you for this awsome package.
I would like to notify a possible mismatch between the documentation and the code.

In the documentation of the return value for `?cubintegrate` I see: 
> error: the estimated relative error for cubature; for Cuba it is the estimated absolute error

Also, in the documentation of the return value for `?hcubature` and `?pcubature` I see:
> error: the estimated relative error

However, after running some tests it seems that all the functions, included `cubintegrate`, `hcubature` and `pcubature`, are returning the absolute error instead. Many thanks!

**Comment by bnaras** [comment]
@eguidotti Thank you.  Updated for the next release.
