### ISSUE TITLE
Error in Makevars

### ISSUE THREAD

**Issue by Jordi-** [bnaras/cubature#33]
There is an error in src/Makevars file. In cuba.ts, instead of:
...
	C="$(CC)" CFLAGS="$(CFLAGS) $(CPICFLAGS) $(PKG_CFLAGS)" ./configure && \
...
it should be
...
	CC="$(CC)" CFLAGS="$(CFLAGS) $(CPICFLAGS) $(PKG_CFLAGS)" ./configure && \
...
i.e., double CC. It may work in most systems, but not of the ones defining the CC variable.

**Comment by bnaras** [comment]
Indeed. This seems to be have been introduced by CRAN when they beat me to a fix on the LTO issue.
